# Advanced NumPy Assignment — Smart Logistics Optimization System

In [1]:
import numpy as np
np.random.seed(42)

distance = np.random.uniform(1, 100, size=(500, 1000))
fuel_rate = np.random.uniform(0.08, 0.25, size=500)
weights = np.random.randint(1, 40, size=(500, 1000))
capacity = np.random.randint(5000, 12000, size=500)
delivery_time = np.random.normal(45, 12, size=(500, 1000))
fuel_price = np.random.uniform(85, 110, size=50)


## Task 1: Print shape, ndim, size, dtype for all datasets

In [2]:
print("Distance Shape =", distance.shape)
print("Fuel Rate Shape =", fuel_rate.shape)
print("Weights Shape =", weights.shape)
print("Capacity Shape =", capacity.shape)
print("Delivery Time Shape =", delivery_time.shape)

print("\nDistance Dimensions =", distance.ndim)
print("Fuel Rate Dimensions =", fuel_rate.ndim)
print("Weights Dimensions =", weights.ndim)
print("Capacity Dimensions =", capacity.ndim)
print("Delivery Time Dimensions =", delivery_time.ndim)

print("\nDistance Size =", distance.size)
print("Fuel Rate Size =", fuel_rate.size)
print("Weights Size =", weights.size)
print("Capacity Size =", capacity.size)
print("Delivery Time Size =", delivery_time.size)

print("\nDistance Data Type =", distance.dtype)
print("Fuel Rate Data Type =", fuel_rate.dtype)
print("Weights Data Type =", weights.dtype)
print("Capacity Data Type =", capacity.dtype)
print("Delivery Time Data Type =", delivery_time.dtype)

Distance Shape = (500, 1000)
Fuel Rate Shape = (500,)
Weights Shape = (500, 1000)
Capacity Shape = (500,)
Delivery Time Shape = (500, 1000)

Distance Dimensions = 2
Fuel Rate Dimensions = 1
Weights Dimensions = 2
Capacity Dimensions = 1
Delivery Time Dimensions = 2

Distance Size = 500000
Fuel Rate Size = 500
Weights Size = 500000
Capacity Size = 500
Delivery Time Size = 500000

Distance Data Type = float64
Fuel Rate Data Type = float64
Weights Data Type = int32
Capacity Data Type = int32
Delivery Time Data Type = float64


## Task 2: Calculate total memory consumed by array

In [4]:
print("Consumed by Distance Memory =", distance.nbytes,"bytes")
print("Consumed by Fuel Rate Memory =", fuel_rate.nbytes,"bytes")
print("Consumed by Weights Memory =", weights.nbytes,"bytes")
print("Consumed by Capacity Memory =", capacity.nbytes,"bytes")
print("Consumed by Delivery Time Memory =", delivery_time.nbytes,"bytes")

Consumed by Distance Memory = 4000000 bytes
Consumed by Fuel Rate Memory = 4000 bytes
Consumed by Weights Memory = 2000000 bytes
Consumed by Capacity Memory = 2000 bytes
Consumed by Delivery Time Memory = 4000000 bytes


## Part 2: Indexing & Slicing

*Extract:*

1. First 10 trucks
2. Last 50 deliveries of each truck
3. Every alternate delivery

Use slicing only.

In [5]:
print("First 10 Trucks =")
print(distance[:10])

print("\nLast 50 Deliveries =")
print(distance[:,-50:])

print("\nAlternate Deliveries =")
print(distance[:,::2])

First 10 Trucks =
[[38.07947177 95.12071633 73.46740024 ... 14.54504446 95.07349803
  45.15457152]
 [19.32815996 54.64819379 87.42163775 ...  7.82684362  6.64841739
  28.93652039]
 [26.90886269 25.45090111 90.71920347 ... 31.66899806 29.71450766
  87.26998938]
 ...
 [ 4.84114602 19.49048029 83.2933347  ... 46.07754623 90.93531724
  11.34355136]
 [72.30652447 69.04101744 10.47966567 ... 97.79356847 11.68453094
  93.26246983]
 [91.44422313 53.0106877  72.76611691 ... 94.72408359 40.35131125
  22.4969    ]]

Last 50 Deliveries =
[[60.45116918 66.83863078 18.36175658 ... 14.54504446 95.07349803
  45.15457152]
 [ 9.77144254 22.84058332 60.22430411 ...  7.82684362  6.64841739
  28.93652039]
 [82.92312567 70.02372881 71.71833694 ... 31.66899806 29.71450766
  87.26998938]
 ...
 [77.08704768 79.35336583 12.36919284 ... 96.65204844 95.52891706
  69.72213447]
 [88.53282913 15.36861871 87.73662261 ... 63.01613795 48.96821262
  58.4720383 ]
 [90.81727575 39.72889623 92.2041779  ... 49.28635359 66.8

In [7]:
print("Truck Indices with Fuel Rate > 0.20 =")
print(np.where(fuel_rate>0.20)[0])

Truck Indices with Fuel Rate > 0.20 =
[  3  10  11  15  20  24  25  34  42  44  50  56  59  64  73  74  82  84
  95  99 106 110 111 113 114 115 116 117 119 122 127 135 136 137 141 143
 146 149 156 159 160 161 163 165 168 181 191 192 203 204 207 210 219 223
 227 228 230 232 233 235 236 239 241 242 244 245 246 248 255 256 258 264
 268 271 274 276 279 284 301 304 305 306 309 314 321 325 327 328 329 330
 340 341 343 345 347 348 354 355 357 358 363 364 366 369 374 377 378 382
 384 385 388 392 393 395 397 411 414 418 423 424 425 426 427 430 433 440
 442 444 445 446 451 452 454 456 458 461 466 472 475 478 479 480 485 487
 489 492 495 497 498]


1. Find trucks whose fuel rate exceeds 0.20.

In [8]:
mask=fuel_rate>0.20
print("Fuel Rates > 0.20 =")
print(fuel_rate[mask])

Fuel Rates > 0.20 =
[0.2486698  0.21234286 0.23763498 0.21169024 0.23220104 0.24101895
 0.23162324 0.21248314 0.21788179 0.2123368  0.23709156 0.21035712
 0.22932418 0.24196909 0.23682547 0.23140498 0.20244992 0.21981505
 0.24392724 0.22101583 0.249142   0.23529382 0.24779961 0.21775406
 0.20228256 0.23322    0.22307393 0.24642215 0.21376475 0.21071343
 0.20732988 0.22703401 0.20935735 0.22791145 0.21868479 0.2032666
 0.2320008  0.24650029 0.24493309 0.24548716 0.21603678 0.22722222
 0.21883987 0.23011477 0.23105154 0.23666374 0.2319285  0.20609068
 0.21223876 0.24408613 0.20507908 0.24838481 0.24985061 0.22197418
 0.20652486 0.23444226 0.24930645 0.20693267 0.22055243 0.22664481
 0.23620244 0.2485071  0.2168056  0.2008798  0.2113046  0.22146855
 0.21107335 0.24662345 0.22383357 0.241052   0.24659845 0.24660154
 0.22883708 0.23686861 0.22360988 0.20896869 0.23996592 0.20007614
 0.20721777 0.24910596 0.22547449 0.20222043 0.22397572 0.2440934
 0.23449734 0.21090219 0.23253275 0.24150901

*Find deliveries where:*

* Distance > 80 km
* Weight > 30 kg

Return their indices.

In [9]:
mask=(distance>80)&(weights>30)
print("Indices (Truck, Delivery) =")
print(np.where(mask))

Indices (Truck, Delivery) =
(array([  0,   0,   0, ..., 499, 499, 499], dtype=int64), array([  1,   7,  35, ..., 852, 991, 996], dtype=int64))


## Task 3: Extract slices

In [10]:
print("Distance Slice (100:110,50:60) =")
print(distance[100:110,50:60])

Distance Slice (100:110,50:60) =
[[ 3.95832148 42.89434542  7.33793153 84.89372777 71.49611576 78.58064148
  62.1305317  66.72385585 12.22759334  6.7585972 ]
 [36.58261969 86.71969424 16.92935903 56.49809086  9.84111344 17.57933572
  90.9685551  99.28653406 99.74915505 80.24342111]
 [82.72232888 58.61912431 85.91369928 20.08545574 60.26626668 33.52631444
  28.03670359 10.86467047 37.11504234  4.45517279]
 [84.09930226 11.00316311 14.85419374 12.80479062 54.94293166 31.10567111
  81.81730573 58.63617561 67.33072746 31.44822659]
 [24.93006875  7.59006162 23.00521975 64.26599501 30.32775872 84.33069337
  62.00874046  5.94882135  9.73118652 28.77876132]
 [66.18112167 97.32598212 89.03118665 33.2951867  22.25957539 96.0728908
  44.93706143 35.8878402  13.47950471 17.48979775]
 [15.11848602 37.37997719 49.65754692 16.12003936 36.82907287 68.87938917
  25.80094563 48.66218186 14.51473943 12.2951993 ]
 [90.1934625  57.80434796 94.56339665 32.46999882 49.87155866  3.24869005
  98.88958354 24.09

## Task 4: Boolean indexing on fuel_rate > 0.20

In [11]:
print("Fuel Rates > 0.20 =")
print(fuel_rate[fuel_rate>0.20])

Fuel Rates > 0.20 =
[0.2486698  0.21234286 0.23763498 0.21169024 0.23220104 0.24101895
 0.23162324 0.21248314 0.21788179 0.2123368  0.23709156 0.21035712
 0.22932418 0.24196909 0.23682547 0.23140498 0.20244992 0.21981505
 0.24392724 0.22101583 0.249142   0.23529382 0.24779961 0.21775406
 0.20228256 0.23322    0.22307393 0.24642215 0.21376475 0.21071343
 0.20732988 0.22703401 0.20935735 0.22791145 0.21868479 0.2032666
 0.2320008  0.24650029 0.24493309 0.24548716 0.21603678 0.22722222
 0.21883987 0.23011477 0.23105154 0.23666374 0.2319285  0.20609068
 0.21223876 0.24408613 0.20507908 0.24838481 0.24985061 0.22197418
 0.20652486 0.23444226 0.24930645 0.20693267 0.22055243 0.22664481
 0.23620244 0.2485071  0.2168056  0.2008798  0.2113046  0.22146855
 0.21107335 0.24662345 0.22383357 0.241052   0.24659845 0.24660154
 0.22883708 0.23686861 0.22360988 0.20896869 0.23996592 0.20007614
 0.20721777 0.24910596 0.22547449 0.20222043 0.22397572 0.2440934
 0.23449734 0.21090219 0.23253275 0.24150901

## Task 5: Find deliveries with distance>80 and weight>30

In [13]:
mask=(distance>80)&(weights>30)
print("Matching Distances with distance >80  and weight >30 are =")
print(distance[mask])

Matching Distances with distance >80  and weight >30 are =
[95.12071633 86.75143843 81.03133746 ... 86.62575603 82.38553915
 98.95472843]


In [15]:
print("Matching Weights with distance >80  and weight >30 are =")
print(weights[mask])

Matching Weights with distance >80  and weight >30 are =
[39 33 33 ... 37 33 36]


# Task 6: Broadcasting

* Compute total fuel consumed per delivery.

        Formula:

            fuel=distance×fuel_rate

In [16]:
fuel=distance*fuel_rate[:,None]
print("Fuel Consumed =")
print(fuel)

Fuel Consumed =
[[ 4.98265018 12.44642408  9.61311536 ...  1.90320047 12.44024563
   5.90841794]
 [ 3.22035309  9.10518541 14.56571874 ...  1.3040662   1.10772322
   4.82124595]
 [ 5.09842354  4.82218349 17.18857196 ...  6.00032663  5.63000923
  16.5350492 ]
 ...
 [23.26847948 12.55072954 20.91187848 ... 23.27467197 23.00421196
  16.78970943]
 [ 6.56462782  4.41993779 20.02623365 ... 15.06785507 11.70884086
  13.98131062]
 [11.10842756 18.85309597  6.40094635 ...  9.39297516 12.73714128
  12.01415578]]



* Calculate fuel cost per delivery.

        Formula:

        cost=fuel×city_fuel_price

Challenge: Map 500 trucks to 50 warehouses.

In [22]:
city_fuel_price = np.random.uniform(90, 110, distance.shape[1])

fuel = distance * fuel_rate[:, None]
cost = fuel * city_fuel_price[None, :]

print("Fuel Cost =")
print(cost)

Fuel Cost =
[[ 449.15631916 1130.81078664 1034.4420198  ...  188.29007628
  1342.75686954  609.87320159]
 [ 290.29570406  827.24498257 1567.37862204 ...  129.01569135
   119.56379351  497.65415008]
 [ 459.59260005  438.11596557 1849.61694756 ...  593.63266153
   607.68362626 1706.76541538]
 ...
 [2097.51522143 1140.28738296 2250.27215372 ... 2302.64222763
  2482.99467378 1733.05171612]
 [ 591.76220714  401.57022626 2154.97024633 ... 1490.71400028
  1263.81158112 1443.16579542]
 [1001.35876597 1712.88429066  688.78897442 ...  929.27888604
  1374.80275474 1240.1139749 ]]


* Calculate total distance traveled per truck.

In [23]:
total_distance=distance.sum(axis=1)
print("Total Distance Per Truck =")
print(total_distance)

Total Distance Per Truck =
[49535.39877869 51194.71321274 50738.16688426 49547.12973096
 49916.42693361 50347.98442967 49837.5750871  48754.69114491
 49163.1725126  50182.70339291 51063.4822607  51019.90319215
 50244.02430705 49868.85162429 50984.39010227 49608.13561554
 51700.2427023  51411.46454539 52641.91544691 50942.16811713
 51885.02724907 50700.60406295 53240.93629018 50775.1525104
 50242.95153472 50610.57880658 49480.75314631 49742.27255204
 49038.2468435  49333.36763744 50865.51423916 51048.87746998
 50452.74243758 49816.8999217  50620.04682087 49465.96017392
 49753.21129849 51027.3051528  50980.58230392 49695.10937813
 50440.75371784 50860.52628537 50878.14085862 49519.97102026
 50036.40702199 50882.52260429 49928.16498405 50681.802159
 48703.43621264 49963.44262429 51421.80075876 51596.46467778
 50196.99649333 50222.93667106 51119.85622444 50490.32436576
 52014.59452049 50201.66023704 50674.12904582 50174.38027112
 49483.46410696 50774.11988807 51705.07488998 49946.31360253


* Calculate average delivery time per truck.

In [24]:
avg_time=delivery_time.mean(axis=1)
print("Average Delivery Time =")
print(avg_time)

Average Delivery Time =
[45.21809592 45.0722776  45.13777291 44.47015878 45.03155726 45.38503285
 45.5052486  44.70365861 44.68514431 45.21451363 45.25102215 44.45205466
 45.55561011 45.12196771 44.97831623 44.98422544 45.56600548 44.76558723
 44.34414946 45.56885272 45.03299658 45.27692571 45.06427815 45.04220799
 44.37096545 45.16153966 44.91357903 44.41828458 44.98654026 44.52861047
 44.3675297  44.73546031 45.09265992 45.02429026 44.24547812 45.63309721
 44.31168811 44.26067057 45.62178927 44.3660236  45.45169193 44.61092958
 45.17454753 45.33665304 45.16895553 45.17002518 45.06492381 45.0565903
 44.99503405 45.11870543 45.27932511 45.08426956 44.35900383 45.10365715
 44.3459397  44.83974723 44.79880114 44.14422811 45.10319834 45.33457058
 45.20629498 45.19027685 44.85211964 44.55943149 44.86320443 45.33396918
 45.19380349 44.65659349 44.82907599 45.16280523 45.20296354 45.08530414
 45.22438505 45.13723106 44.18360191 45.43575075 44.35649821 44.37107982
 44.47516478 44.51077011 45.

In [25]:
fuel=distance*fuel_rate[:,None]
eff=weights.sum(axis=1)/fuel.sum(axis=1)
idx=np.argsort(eff)[-20:][::-1]
print("Top 20 Truck IDs =")
print(idx)

Top 20 Truck IDs =
[ 13 307 112 251 164 428 118  85  39 155  35 316  27 413 121 182  62 202
 365 134]


* Calculate efficiency score:

    Efficiency=TotalWeightDelivered/FuelConsumed

Rank top 20 trucks.

In [26]:
print("Top 20 Efficiency Scores =")
print(eff[idx])

Top 20 Efficiency Scores =
[5.02004852 4.8993169  4.88850106 4.86125607 4.73132756 4.70932279
 4.6065633  4.60380719 4.58897087 4.56332908 4.56200508 4.54779233
 4.53926508 4.50558668 4.49665194 4.46246457 4.39377832 4.39252197
 4.38242054 4.37215502]


### Compute:

    * mean
    * median
    * std
    * variance
    * min
    * max

For:

    * distance
    * weights
    * delivery_time

In [27]:
print("Distance Mean =",np.mean(distance))
print("Distance Median =",np.median(distance))
print("Distance Std =",np.std(distance))
print("Distance Variance =",np.var(distance))
print("Distance Min =",np.min(distance))
print("Distance Max =",np.max(distance))

print("\nWeight Mean =",np.mean(weights))
print("Weight Median =",np.median(weights))
print("Weight Std =",np.std(weights))
print("Weight Variance =",np.var(weights))
print("Weight Min =",np.min(weights))
print("Weight Max =",np.max(weights))

print("\nDelivery Time Mean =",np.mean(delivery_time))
print("Delivery Time Median =",np.median(delivery_time))
print("Delivery Time Std =",np.std(delivery_time))
print("Delivery Time Variance =",np.var(delivery_time))
print("Delivery Time Min =",np.min(delivery_time))
print("Delivery Time Max =",np.max(delivery_time))

Distance Mean = 50.52807875474377
Distance Median = 50.59150316683937
Distance Std = 28.566154319826524
Distance Variance = 816.0251726241436
Distance Min = 1.000220502275013
Distance Max = 99.9998331712345

Weight Mean = 19.962984
Weight Median = 20.0
Weight Std = 11.25905528078373
Weight Variance = 126.766325815744
Weight Min = 1
Weight Max = 39

Delivery Time Mean = 44.979109984264426
Delivery Time Median = 45.00448121768771
Delivery Time Std = 12.003248144250556
Delivery Time Variance = 144.0779660124544
Delivery Time Min = -12.39886890779367
Delivery Time Max = 99.98411491369484


Find percentile statistics:

    25th
    50th
    75th
    90th
    99th

In [28]:
for p in [25,50,75,90,99]:
    print(f"{p}th Percentile =",np.percentile(distance,p))

25th Percentile = 25.75673061477656
50th Percentile = 50.59150316683937
75th Percentile = 75.23774456143124
90th Percentile = 90.05937271623232
99th Percentile = 98.9960091170328


Task 

    Reshape distance matrix into daily batches.

Assume:

    1000 deliveries = 20 days × 50 deliveries/day

In [29]:
daily=distance.reshape(500,20,50)
print("Reshaped Distance =")
print(daily.shape)

Reshaped Distance =
(500, 20, 50)


Compute per-day metrics:

    daily distance
    daily weight
    daily delivery time

Aggregate across axis.

In [32]:
daily_dist = distance.reshape(500, 20, 50).sum(axis=2)
daily_weight = weights.reshape(500, 20, 50).sum(axis=2)
daily_time = delivery_time.reshape(500, 20, -1).mean(axis=2)

print("Daily Distance =")
print(daily_dist)

print("\nDaily Weight =")
print(daily_weight)

print("\nDaily Delivery Time =")
print(delivery_time.shape)
print(delivery_time.size)

Daily Distance =
[[2257.32332674 2497.4660327  2417.58459084 ... 2076.2274548
  2418.88275197 2345.90209305]
 [2712.14763029 2667.81403783 2785.84282677 ... 2803.74641038
  2469.81814731 2440.56175556]
 [2350.82322736 2649.10568452 2790.83844408 ... 2464.06858865
  2549.61156472 2874.55911971]
 ...
 [2123.28148839 2196.82725954 2392.06126598 ... 2723.34456334
  2505.23247603 2160.16644471]
 [2552.80643164 2223.57206305 2549.0389211  ... 2533.82511419
  2822.90147837 3048.39126623]
 [2708.54519196 2591.11423415 2590.98568489 ... 2211.38058077
  2346.57741079 2959.43625983]]

Daily Weight =
[[1012  899  987 ... 1026  972 1038]
 [ 970  980 1026 ... 1057 1134 1075]
 [ 994 1205 1001 ... 1127 1103  898]
 ...
 [1053 1028  894 ... 1046 1072  952]
 [ 984 1021  983 ...  851 1028  910]
 [1087 1134  851 ...  867 1075 1085]]

Daily Delivery Time =
(500, 1000)
500000


Flatten reshaped array back.

Use:

    reshape()
    flatten()
    ravel()

In [33]:
daily=distance.reshape(500,20,50)
print("Reshape =")
print(daily.reshape(500,1000))
print("\nFlatten =")
print(daily.flatten())
print("\nRavel =")
print(daily.ravel())

Reshape =
[[38.07947177 95.12071633 73.46740024 ... 14.54504446 95.07349803
  45.15457152]
 [19.32815996 54.64819379 87.42163775 ...  7.82684362  6.64841739
  28.93652039]
 [26.90886269 25.45090111 90.71920347 ... 31.66899806 29.71450766
  87.26998938]
 ...
 [96.62633308 52.11904688 86.84014514 ... 96.65204844 95.52891706
  69.72213447]
 [27.45430524 18.48487449 83.75285642 ... 63.01613795 48.96821262
  58.4720383 ]
 [58.28759041 98.92503053 33.58672837 ... 49.28635359 66.8336963
  63.04008262]]

Flatten =
[38.07947177 95.12071633 73.46740024 ... 49.28635359 66.8336963
 63.04008262]

Ravel =
[38.07947177 95.12071633 73.46740024 ... 49.28635359 66.8336963
 63.04008262]


Identify overloaded trucks.

Condition:

    TotalWeight>Capacity

    Return truck IDs.

In [34]:
over=weights.sum(axis=1)>capacity
print("Overloaded Truck IDs =")
print(np.where(over)[0])

Overloaded Truck IDs =
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240

Find critical deliveries:

Conditions:

    distance > 90
    delivery_time > 70
    weight > 35

Use combined masks.

In [35]:
mask=(distance>90)&(delivery_time[:,None]>70)&(weights>35)
print("Critical Delivery Indices =")
print(np.where(mask))

Critical Delivery Indices =
(array([  0,   0,   0, ..., 499, 499, 499], dtype=int64), array([  0,   4,   5, ..., 495, 498, 499], dtype=int64), array([661, 682, 761, ...,  97, 319, 133], dtype=int64))


In [38]:
print(distance.shape)
print(mask.shape)

mask = distance > 100

print("Critical Distances =")
print(distance[mask])

(500, 1000)
(500, 500, 1000)
Critical Distances =
[]


Compare execution time:

Method 1:
    Python loop

Method 2:
    NumPy vectorized

In [39]:
import time
start=time.time()
s=0
for row in distance:
    for x in row:
        s+=x
print("Loop Time =",time.time()-start)
start=time.time()
np.sum(distance)
print("NumPy Time =",time.time()-start)

Loop Time = 0.0327908992767334
NumPy Time = 0.0


Create a Truck Risk Score.

    Formula:

Risk=0.35(overload ratio)+0.25(avg delay)+0.25(fuel inefficiency)+0.15(failure probability)

In [40]:
fuel=distance*fuel_rate[:,None]
overload=np.maximum(weights.sum(axis=1)/capacity-1,0)
delay=delivery_time.mean(axis=1)/100
ineff=fuel.sum(axis=1)/fuel.sum(axis=1).max()
fail=np.random.rand(500)
risk=0.35*overload+0.25*delay+0.25*ineff+0.15*fail
print("Truck Risk Score =")
print(risk)

Truck Risk Score =
[0.69482428 0.69327499 0.75576042 1.29808269 0.63525252 0.56177287
 0.64380653 0.69455332 0.89560029 0.56992277 0.65633523 1.11002415
 1.01083256 0.69821976 0.68908299 1.08010746 1.0804675  1.01486676
 0.70489202 0.85983099 0.84635217 0.64034757 0.62203943 0.65442965
 0.80879744 0.74065588 0.65226861 0.84649313 0.6327309  0.7766711
 0.57752949 0.57605262 0.7427835  0.7440647  0.71716011 1.28123114
 0.5391134  1.00349283 0.60202845 0.57887629 0.77747134 0.95655739
 0.78799003 1.09027899 0.62863676 0.77279036 1.30043503 1.19902284
 0.68235913 0.68281783 0.86591303 1.08962807 1.15389607 0.84267598
 0.66415576 1.22835357 0.71977576 0.90153011 0.75549902 0.77780259
 0.92586619 0.92502424 0.89889828 0.68502871 0.98616004 1.17066134
 1.06511357 0.83503379 0.51741989 1.21358337 1.35836165 1.11171417
 1.19582593 0.95174143 0.89329457 0.50970788 0.73621653 1.35887372
 1.0627625  1.19168411 0.7819852  0.99176563 0.97391219 1.26637764
 0.89519416 0.49776033 0.70872286 0.70346464

Implement mini NumPy functions manually:

Create your own version of:

    mean
    std
    normalization

Without using NumPy built-ins.

In [2]:
def my_mean(x):
    return x.sum()/x.size

def my_std(x):
    m=my_mean(x)
    return np.sqrt(((x-m)**2).sum()/x.size)

def normalize(x):
    return (x-x.min())/(x.max()-x.min())

print("Custom Mean =",my_mean(distance))
print("Custom Std =",my_std(distance))
print("Normalized Sample =")
print(normalize(distance[:2,:5]))

Custom Mean = 50.52807875474377
Custom Std = 28.566154319826524
Normalized Sample =
[[0.27497505 1.         0.72477469 0.5569929  0.        ]
 [0.03663577 0.48557243 0.90214056 0.72506529 0.81860583]]
