# Comprehensive NumPy Assignment

**Python for Data Science – NumPy Practice Assignment**

## Instructions
- Use only the NumPy library unless specified otherwise.
- Write clean and well-commented code.
- Display outputs for every question.
- Attempt all questions.
- Explain the logic behind your solutions wherever possible.

## Part 1: Introduction to NumPy

Q1. Import NumPy and display its version.

In [2]:
import numpy as np 
np.__version__


'1.26.4'

Q2. Create arrays: (1) 1-D array from 1 to 10, (2) 3x4 zeros, (3) 3x3 ones, (4) identity matrix of size 5, (5) even numbers from 2 to 20.

In [89]:
import numpy as np

arr1 = np.arange(1, 11)
zeros = np.zeros((3, 4), dtype=int)
ones = np.ones((3, 3), dtype=int)
identity = np.eye(5, dtype=int)
even = np.arange(2, 21, 2)

print("Array from 1 to 10 =")
print(arr1)

print("\nArray of Zeros =")
print(zeros)

print("\nArray of Ones =")
print(ones)

print("\nIdentity Matrix =")
print(identity)

print("\nEven Numbers from 2 to 20 =")
print(even)

Array from 1 to 10 =
[ 1  2  3  4  5  6  7  8  9 10]

Array of Zeros =
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Array of Ones =
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Identity Matrix =
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Even Numbers from 2 to 20 =
[ 2  4  6  8 10 12 14 16 18 20]


Q3. Create arrays using np.arange(), np.linspace(), np.random.rand(), np.random.randint(), and np.full(). Explain the differences.

In [88]:
print("Array using arange() =")
print(np.arange(0, 10, 2))

print("Array using linspace() =")
print(np.linspace(0, 1, 5))

print("Random Array using rand() =")
print(np.random.rand(2, 3))

print("Random Integer Array using randint() =")
print(np.random.randint(1, 10, (2, 2)))

print("Array filled with 7 using full() =")
print(np.full((2, 3), 7))

Array using arange() =
[0 2 4 6 8]
Array using linspace() =
[0.   0.25 0.5  0.75 1.  ]
Random Array using rand() =
[[0.49229405 0.10059073 0.73613381]
 [0.48054147 0.4783847  0.18290001]]
Random Integer Array using randint() =
[[9 2]
 [2 4]]
Array filled with 7 using full() =
[[7 7 7]
 [7 7 7]]


## Array Attributes

Q4. Given arr = np.array([[10,20,30],[40,50,60],[70,80,90]]), find shape, size, dimension, dtype, itemsize, and memory occupied.

In [87]:
arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

print("Shape =", arr.shape)
print("Size =", arr.size)
print("Dimensions =", arr.ndim)
print("Data Type =", arr.dtype)
print("Item Size =", arr.itemsize, "bytes")
print("Total Bytes =", arr.nbytes, "bytes")

Shape = (3, 3)
Size = 9
Dimensions = 2
Data Type = int32
Item Size = 4 bytes
Total Bytes = 36 bytes


Q5. Convert the array into float, integer, and boolean types.

In [86]:
arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

print("Float Data Type =")
print(arr.astype(float))

print("Integer Data Type =")
print(arr.astype(int))

print("Boolean Data Type =")
print(arr.astype(bool))

Float Data Type =
[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
Integer Data Type =
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Boolean Data Type =
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Part 3: Indexing and Slicing

###### Creata a 4x4x2 array and display the elements, rows and columns

In [85]:
arr=np.arange(1,33).reshape(4,4,2)
print(arr)
print('Rows:\n',arr[0])
print('Columns first slice:\n',arr[:,:,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]]
Rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Columns first slice:
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]


Q7. Reverse the entire array, rows, and columns.

In [83]:
arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

print("Reverse Rows and Columns =")
print(arr[::-1, ::-1])

print("Reverse Rows =")
print(arr[::-1])

print("Reverse Columns =")
print(arr[:, ::-1])

Reverse Rows and Columns =
[[90 80 70]
 [60 50 40]
 [30 20 10]]
Reverse Rows =
[[70 80 90]
 [40 50 60]
 [10 20 30]]
Reverse Columns =
[[30 20 10]
 [60 50 40]
 [90 80 70]]


Q8. Replace values greater than 30 with 0.

In [82]:
arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

arr[arr > 30] = 0

print("Array after replacing values greater than 30 with 0 =")
print(arr)

Array after replacing values greater than 30 with 0 =
[[10 20 30]
 [ 0  0  0]
 [ 0  0  0]]


## Part 4: Reshaping and Flattening

Q9. Create an array from 1 to 24 and reshape it into different dimensions. Compare flatten() and ravel().

In [80]:
arr = np.arange(1, 25)

print("Reshape to (2,12) =\n", arr.reshape(2, 12))
print("Reshape to (3,8) =\n", arr.reshape(3, 8))
print("Flatten Array =\n", arr.flatten())
print("Ravel Array =\n", arr.ravel())

Reshape to (2,12) =
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
Reshape to (3,8) =
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Flatten Array =
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Ravel Array =
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


Q10. Demonstrate transpose(), swapaxes(), and reshape(-1).

In [79]:
arr = np.arange(1, 13).reshape(3, 4)

print("Transpose of Array =\n", arr.T)
print("Swap Axes (0,1) =\n", np.swapaxes(arr, 0, 1))
print("Reshaped to 1D =\n", arr.reshape(-1))

Transpose of Array =
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Swap Axes (0,1) =
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Reshaped to 1D =
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


## Part 5: Mathematical Operations

Q11. Perform arithmetic operations between arrays.

In [77]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", a / b)

Addition = [5 7 9]
Subtraction = [-3 -3 -3]
Multiplication = [ 4 10 18]
Division = [0.25 0.4  0.5 ]


Q12. Find square root, exponential, logarithm, sine, cosine, and tangent values.

In [76]:
a = np.array([1, 4, 9])

print("Square Root =", np.sqrt(a))
print("Exponential =", np.exp(a))
print("Natural Log =", np.log(a))
print("Sine =", np.sin(a))
print("Cosine =", np.cos(a))
print("Tangent =", np.tan(a))

Square Root = [1. 2. 3.]
Exponential = [2.71828183e+00 5.45981500e+01 8.10308393e+03]
Natural Log = [0.         1.38629436 2.19722458]
Sine = [ 0.84147098 -0.7568025   0.41211849]
Cosine = [ 0.54030231 -0.65364362 -0.91113026]
Tangent = [ 1.55740772  1.15782128 -0.45231566]


Q13. Compare arrays using relational operators.

In [75]:
a=np.array([1,2,3]);
b=np.array([2,2,1]);

print("a > b =", a > b)
print("a == b =", a == b)
print("a <= b =", a <= b)

a > b = [False False  True]
a == b = [False  True False]
a <= b = [ True  True False]


Q14. Perform Dot product of multi dimensional array

In [73]:
a=np.array([[1,2],[3,4]]);
b=np.array([[5,6],[7,8]]);
print("Dot Product =\n", np.dot(a, b))

Dot Product =
 [[19 22]
 [43 50]]


## Part 7: Aggregation Functions

Q15. Find sum, mean, median, standard deviation, variance, maximum, and minimum.

In [70]:
a = np.array([1, 2, 3, 4, 5])

print("Sum =", np.sum(a))
print("Mean =", np.mean(a))
print("Median =", np.median(a))
print("Standard Deviation =", np.std(a))
print("Variance =", np.var(a))
print("Maximum =", np.max(a))
print("Minimum =", np.min(a))

Sum = 15
Mean = 3.0
Median = 3.0
Standard Deviation = 1.4142135623730951
Variance = 2.0
Maximum = 5
Minimum = 1


Q16. Find row-wise and column-wise statistics.

In [69]:
a = np.array([1, 2, 3, 4, 5])

print("Sum =", np.sum(a))
print("Mean =", np.mean(a))
print("Median =", np.median(a))
print("Standard Deviation =", np.std(a))
print("Variance =", np.var(a))
print("Maximum =", np.max(a))
print("Minimum =", np.min(a))

Sum = 15
Mean = 3.0
Median = 3.0
Standard Deviation = 1.4142135623730951
Variance = 2.0
Maximum = 5
Minimum = 1


Q17. Find cumulative sum and cumulative product.

In [67]:
a=np.array([1,2,3,4]);
print(f"Cumalative sum: {np.cumsum(a)}");
print(f"Cumalative prod: {np.cumprod(a)}")

Cumalative sum: [ 1  3  6 10]
Cumalative prod: [ 1  2  6 24]


## Part 8: Sorting and Searching

Q18. Sort arrays and find indices and elements satisfying conditions.

In [64]:
a=np.array([4,2,7,1,5]);
print(f"Sorted order : {np.sort(a)}");
print(f"Arg sort: {np.argsort(a)}");
print(f"Value greater than 3 are : {a[a>3]}");

Sorted order : [1 2 4 5 7]
Arg sort: [3 1 0 4 2]
Value greater than 3 are : [4 7 5]


Q19. Find unique elements and their frequencies.

In [58]:
a=np.array([1,10,40,50,40,40,2,2,3,3,3]);
u,c=np.unique(a,return_counts=True);
print(f"unique elem : {u} \ntheir respective freq : {c}")

unique elem : [ 1  2  3 10 40 50] 
their respective freq : [1 2 3 1 3 1]


## Part 9: Stacking and Splitting

Q20. Demonstrate stacking methods.

In [3]:
a = np.array([[1, 2],[3, 4]])

b = np.array([[5, 6],[7, 8]])

print("Vertical Stack =")
print(np.vstack((a, b)))

print("\nHorizontal Stack =")
print(np.hstack((a, b)))

Vertical Stack =
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack =
[[1 2 5 6]
 [3 4 7 8]]


Q21. Split arrays into equal parts.

In [4]:
a=np.arange(8);
print(np.split(a,2))

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]


## Part 10: Random Module

Q22. Generate random numbers and matrices.

In [8]:
print(np.random.rand(3));
print(np.random.randint(1,10,(3,3)))

[0.95120842 0.46325875 0.43810944]
[[5 3 7]
 [7 4 1]
 [2 9 1]]


Q23. Simulate rolling a die 100 times and analyze frequencies.

In [10]:
rolls=np.random.randint(1,7,100);
u,c=np.unique(rolls,return_counts=True);
for i,j in zip(u,c):
    print(f"Number {i}: rolled {j} times");

Number 1: rolled 18 times
Number 2: rolled 12 times
Number 3: rolled 17 times
Number 4: rolled 18 times
Number 5: rolled 11 times
Number 6: rolled 24 times


## Part 11: Boolean Masking and Filtering

Q24. Extract values based on conditions.

In [11]:
a=np.arange(10);
print(a[a%2==0])

[0 2 4 6 8]


Q25. Replace odd numbers with -1.

In [12]:
a=np.arange(10);

a[a%2==1]=-1;

print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Part 12: Missing Values

Q26. Detect and replace missing values.

In [13]:
a=np.array([1,np.nan,3]);
print(np.nan_to_num(a,nan=0))

[1. 0. 3.]


## Part 13: Linear Algebra

Q27. Perform matrix operations.

In [14]:
A=np.array([[1,2],[3,4]]);
B=np.array([[5,6],[7,8]]);
print("Addition =")
print(A + B)

print("\nSubtraction =")
print(A - B)

print("\nMatrix Multiplication =")
print(A @ B)

Addition =
[[ 6  8]
 [10 12]]

Subtraction =
[[-4 -4]
 [-4 -4]]

Matrix Multiplication =
[[19 22]
 [43 50]]


Q28. Find determinant, inverse, transpose, eigenvalues, and eigenvectors.

In [15]:
A=np.array([[1,2],[3,4]]);
print("Determinant =")
print(np.linalg.det(A))

print("\nInverse Matrix =")
print(np.linalg.inv(A))

print("\nTranspose Matrix =")
print(A.T)

print("\nEigenvalues and Eigenvectors =")
print(np.linalg.eig(A));

Determinant =
-2.0000000000000004

Inverse Matrix =
[[-2.   1. ]
 [ 1.5 -0.5]]

Transpose Matrix =
[[1 3]
 [2 4]]

Eigenvalues and Eigenvectors =
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


Q29. Solve a system of linear equations using NumPy.

In [16]:
A=np.array([[2,1],[1,-1]]);
b=np.array([5,1]);
sol = np.linalg.solve(A,b);
print(f"x = {sol[0]}");
print(f"y = {sol[1]}");

x = 2.0
y = 1.0


## Part 14: Advanced NumPy

Q30. Demonstrate fancy indexing, boolean indexing, where(), argmax(), argmin(), and argsort().

In [17]:
a = np.array([10, 20, 30, 40, 50])

print("Elements at Indices [0, 2, 4] =")
print(a[[0, 2, 4]])

print("\nElements Greater Than 25 =")
print(a[a > 25])

print("\nIndices of Elements Greater Than 25 =")
print(np.where(a > 25))

print("\nIndex of Maximum Element =")
print(np.argmax(a))

print("\nIndex of Minimum Element =")
print(np.argmin(a))

print("\nIndices that Sort the Array =")
print(np.argsort(a))

Elements at Indices [0, 2, 4] =
[10 30 50]

Elements Greater Than 25 =
[30 40 50]

Indices of Elements Greater Than 25 =
(array([2, 3, 4], dtype=int64),)

Index of Maximum Element =
4

Index of Minimum Element =
0

Indices that Sort the Array =
[0 1 2 3 4]


Q31. Use tile(), repeat(), clip(), and diag().

In [18]:
a = np.array([1, 2, 3])

print("Tile Array =")
print(np.tile(a, 2))

print("\nRepeat Elements =")
print(np.repeat(a, 2))

print("\nClipped Array (2 to 3) =")
print(np.clip(a, 2, 3))

print("\nDiagonal Matrix =")
print(np.diag([1, 2, 3]))

Tile Array =
[1 2 3 1 2 3]

Repeat Elements =
[1 1 2 2 3 3]

Clipped Array (2 to 3) =
[2 2 3]

Diagonal Matrix =
[[1 0 0]
 [0 2 0]
 [0 0 3]]


Q32. Create a checkerboard pattern.

In [19]:
a=np.zeros((8,8),int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q33. Write a line of code to extract the inner 2×2 submatrix (excluding the border rows and columns).

In [20]:
a=np.arange(1,17).reshape(4,4)
print(a[1:3,1:3])

[[ 6  7]
 [10 11]]


Q34. Reshape a 1D array of 12 elements (from Step 4) into a 3×4 2D matrix.

In [22]:
a=np.arange(1,13)
print(a.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Q35 Create a 3×3 identity matrix.

In [23]:
print("Identity Matrix (3 × 3) =")
print(np.eye(3, dtype=int))

Identity Matrix (3 × 3) =
[[1 0 0]
 [0 1 0]
 [0 0 1]]


Q35. Stack two identical 2×2 arrays of ones vertically.

In [24]:
a = np.ones((2, 2), dtype=int)

print("Vertical Stack of Matrix =")
print(np.vstack((a, a)))

Vertical Stack of Matrix =
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


Q36. Create Matrix A with dimensions 2×3 and Matrix B with dimensions 3×2.

In [25]:
A=np.array([[1,2,3],[4,5,6]]);
B=np.array([[7,8],[9,10],[11,12]])
print("Matrix A =")
print(A)

print("\nMatrix B =")
print(B)

Matrix A =
[[1 2 3]
 [4 5 6]]

Matrix B =
[[ 7  8]
 [ 9 10]
 [11 12]]


Q37. Perform a matrix multiplication (A × B) to yield a 2×2 matrix result.

In [26]:
print("Matrix Multiplication (A × B) =")
print(A @ B)

Matrix Multiplication (A × B) =
[[ 58  64]
 [139 154]]


# Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [20]:
#Complete the following code in order to add the vector v to each row of a matrix x:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1,0,1])
y = np.zeros(x.shape)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i,j] = v[j] + x[i][j]
print(y)

[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


In [5]:
print('Assignment Completed')

Assignment Completed
